sasl.mechanism=PLAIN
security.protocol=SASL_SSL
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="QRCT7SUSU7NG3NIY" password="ZZ6siYRsaHgdbTTGVZyZoe/1nhNJDB1p/of82PnyNQXKq0ZZ2UWnsieKl69jxZWt";
