sasl.mechanism=PLAIN
security.protocol=SASL_SSL
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="QRCT7SUSU7NG3NIY" password="ZZ6siYRsaHgdbTTGVZyZoe/1nhNJDB1p/of82PnyNQXKq0ZZ2UWnsieKl69jxZWt";
>>>>>>> 197909dd93c158ad6506c53177e161e80d7c3a95
